time.sleep(1)
print("Loading...")
time.sleep(0.5)
ram1 = "32mb"
rom1 = "100mb"
print("RAM:" + ram1)
print("ROM:" + rom1)
time.sleep(1)
print("WELCOME BACK TO THE Vivi OS")
print("VERSION 2.0 release('on Github')")
print("LOLOLOL 2023-2026 all rights (not) reserved")
while True:
    command1 = input("Input the command:")
    if command1 == "about the OS":
        print("RELEASE('on Github')")
        print("deveplover in 2024")
    if command1 == "calculator":
        calc1 = float(input("Enter the 1-st number: "))
        calc2 = float(input("Enter the 2-nd number: "))
        calc3 = input("Enter the action(+,-,/,*): ")
        if calc3 == "+":
            answer1 = (calc1 + calc2)
            print(str(answer1))
        if calc3 == "-":
            answer1 = (calc1 - calc2)
            print(str(answer1))
        if calc3 == "/":
            answer1 = (calc1 / calc2)
            print(str(answer1))
        if calc3 == "*":
            answer1 = (calc1 * calc2)
            print(str(answer1))
    if command1 == "info":
        print("commands:")
        print("calculator")
        print("about the OS")
        print("python's virus")
        print("year")
        print("next year")
        print("WOW")
    if command1 == "python's virus":
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.5)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.5)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.5)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.5)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.5)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.5)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.5)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.5)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.5)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.5)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.5)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.5)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        time.sleep(0.1)
        print("🐍🐍🐍🐍🐍")
        print("╔╗╔╗╔══╗╔╗╔╗───╔══╗─╔══╗╔══╗╔══╗╔═══╗╔══╗─╔╗╔╗╔╗")
        print("║║║║║╔╗║║║║║───║╔╗╚╗║╔╗║╚═╗║║╔═╝║╔══╝║╔╗╚╗║║║║║║")
        print("║╚╝║║║║║║║║║───║║╚╗║║║║║──║╚╝║──║╚══╗║║╚╗║║║║║║║")
        print("╚═╗║║║║║║║║║───║║─║║║║║║──║╔╗║──║╔══╝║║─║║╚╝╚╝╚╝")
        print("─╔╝║║╚╝║║╚╝║───║╚═╝║║╚╝║╔═╝║║╚═╗║╚══╗║╚═╝║╔╗╔╗╔╗")
        print("─╚═╝╚══╝╚══╝───╚═══╝╚══╝╚══╝╚══╝╚═══╝╚═══╝╚╝╚╝╚╝")
        time.sleep(0.5)
        print("╔════╗╔═══╗╔═══╗╔═══╗───╔═══╗╔══╗─╔══╗─╔══╗╔╗╔══╗╔══╗╔╗╔╗─╔══╗╔╗╔╗╔╗╔╗╔╗")
        print("╚═╗╔═╝║╔══╝║╔══╝║╔═╗║───╚══╗║║╔╗║─║╔╗║─║╔╗║║║║╔═╝║╔═╝║║║║─║╔╗║║║║║║║║║║║")
        print("──║║──║╚══╗║╚══╗║╚═╝║────╔═╝║║╚╝║─║║║║─║║║║║╚╝║──║║──║║║║─║║║║║║║║║║║║║║")
        print("──║║──║╔══╝║╔═╗║╚╗╔╗║────╚═╗║║╔╗║─║║║║─║║║║║╔╗║──║║──║║╔║─║║║║║║╔║╚╝╚╝╚╝")
        print("──║║──║╚══╗║╚═╝║─║║║║───╔══╝║║║║║╔╝╚╝╚╗║╚╝║║║║╚═╗║╚═╗║╚╝║╔╝║║║║╚╝║╔╗╔╗╔╗")
        print("──╚╝──╚═══╝╚═══╝─╚╝╚╝───╚═══╝╚╝╚╝╚════╝╚══╝╚╝╚══╝╚══╝╚══╝╚═╝╚╝╚══╝╚╝╚╝╚╝")
    if command1 == "year":
        print("@@@@@@ **** @@@@@@ %%%%%%")
        time.sleep(0.1)
        print("     @ *  *      @ %     ")
        time.sleep(0.1)
        print("   @   *  *    @   %%%%%%")
        time.sleep(0.1)
        print(" @     *  *  @          %")
        time.sleep(0.1)
        print("@@@@@@ **** @@@@@@ %%%%%%")
    if command1 == "next year":
        print("@@@@@@ **** @@@@@@  %%%%%%")
        time.sleep(0.1)
        print("     @ *  *      @  %     ")
        time.sleep(0.1)
        print("   @   *  *    @    %%%%%%")
        time.sleep(0.1)
        print(" @     *  *  @      %    %")
        time.sleep(0.1)
        print("@@@@@@ **** @@@@@@  %%%%%%")
    if command1 == "WOW":
        print("@      @      @    #########    @      @      @")
        time.sleep(0.2)
        print(" @     @     @     ##     ##     @     @     @")
        time.sleep(0.2)
        print("  @    @    @      ##     ##      @    @    @")
        time.sleep(0.2)
        print("   @  @ @  @       ##     ##       @  @ @  @")
        time.sleep(0.2)
        print("    @@   @@        #########        @@   @@")
        time.sleep(0.2)

        print("@      @      @    #########    @      @      @")
        time.sleep(0.2)
        print(" @     @     @     ##     ##     @     @     @")
        time.sleep(0.2)
        print("  @    @    @      ##     ##      @    @    @")
        time.sleep(0.2)
        print("   @  @ @  @       ##     ##       @  @ @  @")
        time.sleep(0.2)
        print("    @@   @@        #########        @@   @@")
        time.sleep(0.2)

        print("@      @      @    #########    @      @      @")
        time.sleep(0.2)
        print(" @     @     @     ##     ##     @     @     @")
        time.sleep(0.2)
        print("  @    @    @      ##     ##      @    @    @")
        time.sleep(0.2)
        print("   @  @ @  @       ##     ##       @  @ @  @")
        time.sleep(0.2)
        print("    @@   @@        #########        @@   @@")



